# Generated by Django 5.0.6 on 2025-05-09 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.CharField(help_text='Ruta relativa a static/, ej: img/ficus.jpg', max_length=100),
        ),
    ]
